name: Bug Report
description: File a bug or crash report
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a bug report, please fill out as much detail as possible.
  - type: checkboxes
    id: latestversion
    attributes:
      label: Are you on the latest version of UnityExplorer?
      description: If not, you must update first.
      options:
        - label: Yes, I'm on the latest version of UnityExplorer.
          required: true
  - type: dropdown
    id: version
    attributes:
      label: Which release are you using?
      description: Please select your environment for UnityExplorer.
      options:
        - BepInEx IL2CPP
        - BepInEx 6.X Mono
        - BepInEx 5.X Mono
        - MelonLoader IL2CPP
        - MelonLoader Mono
        - Standalone IL2CPP
        - Standalone Mono
    validations:
      required: true
  - type: textarea
    id: game
    attributes:
      label: Which game did this occur on?
      description: Please tell us the name of the game. If it's a personal or private project, just let us know the Unity version.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue.
      description: What happened? Should something else have happened instead? Please provide steps to reproduce the issue if possible.
      placeholder: Tell us what you see! 
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant logs and stack traces.
        * Unity log: `%userprofile%\AppData\LocalLow\{Company}\{Game}\Player.log` or `output_log.txt`
        * BepInEx: `BepInEx\LogOutput.log`
        * MelonLoader: `MelonLoader\latest.log`
        * Standalone: `{DLL_Location}\UnityExplorer\Logs\` (pick the most recent one)
      render: shell
    validations:
      required: false