name: New feature or enhancement
description: Suggest or discuss a feature or enhancement for UnityExplorer
title: "[Enhancement]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to discuss UnityExplorer, please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Describe the new feature or enhancement
      description: |
        Please go into as much detail as necessary in describing the new feature or enhancement.
        If providing examples or suggestions for the required C# code, please use syntax-highlighted code blocks.
    validations:
      required: true
